Update for latest JuliaGeo/GDAL (#48)
* update for latest version of gdal.jl

* don't throw away test files

people who test will want to keep them anyway, and people who don’t
won’t be bothered by the bloat

* fix travis script

* remove projection tests for now

* delete empty test REQUIRE

* add master testset

this will give aligned and more compact printing of test results

* remove workarounds

* remove unnecessary checknull

* precompile

this seems to fix GDAL_DATA issues reported in https://github.com/JuliaGeo/GDAL.jl/issues/49

* add Compat to REQUIRE

* use Base.Dates

This works on 0.6, on 0.7 it should be `use Dates`, but this is needed to get around this error in 0.7:
UndefVarError: Date not defined

* fix UndefVarError on 0.7

* make tests more robust