use Base.Dates
This works on 0.6, on 0.7 it should be `use Dates`, but this is needed to get around this error in 0.7:
UndefVarError: Date not defined